import type { ApplicationData } from "@/features/apply/schema/application";
import { emptyApplication } from "@/features/apply/schema/defaults";

/** Obviously fake data, used by the demo "fill sample data" button and the sample applicants. */

export const SAMPLE_SIGNATURE =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="100" viewBox="0 0 320 100"><path d="M12 68 C 36 14, 58 96, 84 44 S 130 18, 150 62 S 214 92, 306 28" fill="none" stroke="#0c0e12" stroke-width="3" stroke-linecap="round"/></svg>',
  );

const isoDaysAgo = (days: number) => new Date(Date.now() - days * 86_400_000).toISOString().slice(0, 10);

export function sampleApplication(overrides: Partial<ApplicationData> = {}): ApplicationData {
  return {
    ...emptyApplication(),
    position: "Company driver",
    over18: "yes",
    proofOfAge: "yes",
    firstName: "Jordan",
    lastName: "Whitfield",
    middleInitial: "T",
    dob: "1986-04-12",
    street: "412 Maple Street",
    city: "Russellville",
    state: "AR",
    zip: "72801",
    phone: "(479) 555-0142",
    email: "jordan.whitfield@example.com",
    ssn: "123-45-6789",
    cellCarrier: "Verizon",
    smoker: "no",
    cdlNumber: "900123456",
    cdlState: "AR",
    cdlYears: "9",
    addresses: [{ street: "412 Maple Street", city: "Russellville", state: "AR", zip: "72801" }],
    legalRight: "yes",
    legalRightHowLong: "Lifelong U.S. citizen",
    canProveRight: "yes",
    felony: "no",
    pendingCharges: "no",
    probation: "no",
    emergencyContacts: [{ name: "Casey Whitfield", phone: "(479) 555-0177", relationship: "Spouse" }],
    nameChanged: "no",
    skills: "Tanker endorsement, hazmat, 9 years OTR and regional.",
    workedHereBefore: "no",
    appliedBefore: "no",
    employedNow: "yes",
    howHeard: "Referred by a Propel driver",
    expectedPay: "",
    dismissed: "no",
    contactEmployer: "yes",
    veteran: "no",
    layoff: "no",
    unableToPerform: "no",
    references: [{ name: "Pat Morgan", addressPhone: "88 Oak Lane, Dardanelle, AR / (479) 555-0119", relationship: "Former supervisor" }],
    employers: [
      {
        employer: "Ozark Bulk Haulers",
        startDate: isoDaysAgo(1300),
        endDate: isoDaysAgo(400),
        current: false,
        street: "1200 Industrial Blvd",
        city: "Fort Smith",
        state: "AR",
        zip: "72901",
        position: "Tanker driver",
        pay: "0.62",
        payPer: "mile",
        contact: "Dana Reyes, (479) 555-0100",
        reasonLeaving: "Looking for more home time",
        fmcsa: "yes",
        safetySensitive: "yes",
      },
      {
        employer: "River Valley Transport",
        startDate: isoDaysAgo(400),
        endDate: "",
        current: true,
        street: "55 Dock Road",
        city: "Russellville",
        state: "AR",
        zip: "72802",
        position: "Tanker driver",
        pay: "0.65",
        payPer: "mile",
        contact: "Lee Carter, (479) 555-0166",
        reasonLeaving: "",
        fmcsa: "yes",
        safetySensitive: "yes",
      },
    ],
    hasAccidents: "no",
    accidents: [],
    hasConvictions: "no",
    convictions: [],
    ackNotices: true,
    ackEsign: true,
    ackFcra: true,
    ackRelease: true,
    ackMvr: true,
    ackDrug: true,
    licenseExpiry: isoDaysAgo(-900),
    ackLicense: true,
    printedName: "Jordan T Whitfield",
    signature: SAMPLE_SIGNATURE,
    ...overrides,
  };
}
