import type { ApplicationData } from "./application";

/** Factories for the blank rows the repeaters append. */
export const blankRow = {
  address: () => ({ street: "", city: "", state: "", zip: "" }),
  contact: () => ({ name: "", phone: "", relationship: "" }),
  school: () => ({ school: "", address: "", years: "", degree: "", course: "" }),
  reference: () => ({ name: "", addressPhone: "", relationship: "" }),
  employer: () => ({
    employer: "",
    startDate: "",
    endDate: "",
    current: false,
    street: "",
    city: "",
    state: "",
    zip: "",
    position: "",
    pay: "",
    payPer: "",
    contact: "",
    reasonLeaving: "",
    fmcsa: "",
    safetySensitive: "",
  }),
  accident: () => ({ date: "", details: "", fatalities: "no", injuries: "no" }),
  conviction: () => ({ location: "", date: "", charge: "", penalty: "" }),
};

export function emptyApplication(): ApplicationData {
  return {
    position: "",
    over18: "",
    proofOfAge: "",
    firstName: "",
    lastName: "",
    middleInitial: "",
    dob: "",
    street: "",
    city: "",
    state: "",
    zip: "",
    phone: "",
    email: "",
    ssn: "",
    cellCarrier: "",
    smoker: "",
    cdlNumber: "",
    cdlState: "",
    cdlYears: "",
    addresses: [blankRow.address()],
    legalRight: "",
    legalRightHowLong: "",
    canProveRight: "",
    felony: "",
    pendingCharges: "",
    probation: "",
    backgroundExplain: "",
    emergencyContacts: [blankRow.contact()],
    education: [],
    nameChanged: "",
    nameChangeDetails: "",
    skills: "",
    workedHereBefore: "",
    workedHereWhere: "",
    workedHereFrom: "",
    workedHereTo: "",
    workedHerePosition: "",
    workedHereRate: "",
    workedHerePer: "",
    workedHereReason: "",
    appliedBefore: "",
    appliedBeforeWhen: "",
    employedNow: "",
    lastEmployed: "",
    howHeard: "",
    expectedPay: "",
    dismissed: "",
    dismissedExplain: "",
    contactEmployer: "",
    contactEmployerExplain: "",
    veteran: "",
    veteranBranch: "",
    veteranFrom: "",
    veteranTo: "",
    veteranDischarge: "",
    layoff: "",
    layoffExplain: "",
    unableToPerform: "",
    unableExplain: "",
    references: [blankRow.reference()],
    employers: [blankRow.employer()],
    hasAccidents: "",
    accidents: [blankRow.accident()],
    hasConvictions: "",
    convictions: [blankRow.conviction()],
    ackNotices: false,
    ackEsign: false,
    ackFcra: false,
    ackRelease: false,
    ackMvr: false,
    ackDrug: false,
    licenseExpiry: "",
    ackLicense: false,
    printedName: "",
    signature: "",
  };
}

/** Drop rows and stale values the applicant said don't apply, so stored data matches what they meant. */
export function normalizeApplication(data: ApplicationData): ApplicationData {
  return {
    ...data,
    employers: data.employers.map((e) => (e.current ? { ...e, endDate: "", reasonLeaving: "" } : e)),
    accidents: data.hasAccidents === "yes" ? data.accidents : [],
    convictions: data.hasConvictions === "yes" ? data.convictions : [],
  };
}
